version: '3.8'

services:

  discovery-server:
    image: discovery-server
    ports:
      - "8761:8761"

  api-gateway:
    image: api-gateway
    ports:
      - "8080:8080"
    depends_on:
      - discovery-server

  product-service:
    image: product-service
    ports:
      - "8081:8081"
    depends_on:
      - discovery-server

  user-service:
    image: user-service
    ports:
      - "8083:8083"
    depends_on:
      - discovery-server

  order-service:
    image: order-service
    ports:
      - "8082:8082"
    depends_on:
      - discovery-server